title: "Zhiyuan Sun"
description: "PhD Student, Cheriton School of Computer Science, University of Waterloo"

url: "https://zhiyuuans.github.io"
baseurl: ""   # keep empty for username.github.io

author:
  name: "Zhiyuan Sun"
  email: "zhiyuan.sun@uwaterloo.ca"
  affiliation: "Cheriton School of Computer Science, University of Waterloo"
  github: "https://github.com/ZhiyuuanS"
  google_scholar: "https://scholar.google.com/citations?hl=en&user=_mKupC0AAAAJ"
  x: "https://x.com/ZhiyuuanS"
